name: Playwright tests
on:
  push:
    branches: [ main ]
jobs: 
  playwrighttests: 
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.50.0-noble
      env:
        ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}

    steps:
     - name: Checkout repository
       uses: actions/checkout@v2
     - name: Run tests
       run: |
        echo "Start shopping store"
        chmod +x ./shopping-store-linux-amd64
        ./shopping-store-linux-amd64 &
        echo "Install dependencies"
        npm ci
        echo "Run tests"
        npm run test:ci